from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.remote.webelement import WebElement
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys

import time
import pytest
# import allure
# @allure.severity(allure.severity_level.NORMAL)
@pytest.fixture()
def test_chupshop():
    global driver
    serv_obj=Service("C:\Drivers\chromedriver.exe")
    driver = webdriver.Chrome(service=serv_obj)
    driver.get("https://qa2.chups.com/")
    driver.maximize_window()
    time.sleep(5)
    driver.find_element(By.ID, "exampleFormControlInput1").send_keys("qa_testing@qa.com")
    driver.find_element(By.ID, "exampleFormControlInput2").send_keys("qa_123!@")
    driver.find_element(By.XPATH, "//span[contains(text(),'show')]").click()
    time.sleep(4)
    driver.find_element(By.XPATH, "//button[contains(text(),'Sign In')]").click()
    time.sleep(15)
@pytest.mark.skip()
def test_addregion(test_chupshop):
    driver.find_element(By.XPATH, "//button[contains(text(),'Add Region')]").click()
    driver.find_element(By.ID,"searchInput").send_keys("Texas1")
    time.sleep(3)
    driver.find_element(By.XPATH,"//button[@class='outline-btn px-5 ml-3 mt-2']").click()
    time.sleep(5)
    for i in range(2):
        driver.find_element(By.XPATH,"//button[@class='btn-close']").click()
        time.sleep(2)
@pytest.mark.skip
def test_addkitchen(test_chupshop):
    driver.find_element(By.XPATH,"//button[contains(text(),'Add Cloud Kitchen')]").click()
    time.sleep(5)
    driver.find_element(By.NAME,"Kitchen_Name").send_keys("red Social Kitchens")
    time.sleep(5)
    driver.find_element(By.NAME,"address1").send_keys("3244")
    time.sleep(5)
    driver.find_element(By.XPATH,"//ul[@style='display: block;']/li[1]").click()
    driver.find_element(By.ID,"partitioned").send_keys("12:30")
    time.sleep(4)
    driver.find_element(By.XPATH,"//input[@placeholder='hh:mm']").send_keys("01:00")
    driver.find_element(By.XPATH,"//span[contains(text(),'Pick-up')]").click()
    driver.find_element(By.XPATH,"//span[contains(text(),'Dine-In')]").click()


    driver.find_element(By.NAME,"slotName").send_keys("Breakfast")
    driver.find_element(By.NAME,"openTime").send_keys("08:00")
    driver.find_element(By.NAME,"closeTime").send_keys("11:30")
    time.sleep(10)
    driver.find_element(By.XPATH,"//div[@class='w-100 d-flex justify-content-start align-items-center mt-2 mx-2 mt-md-2']/img[2]").click()
    input_elements=driver.find_elements(By.XPATH,"//input[@name='slotName']")
    # input_elements[0].send_keys("BF")
    input_elements[1].send_keys("Lunch")
    driver.find_element(By.XPATH,"//button[contains(text(),'Set This Time For All Days')]").click()
    time.sleep(4)
    prompt_alert = driver.switch_to.alert
    prompt_alert.accept()
    time.sleep(5)
    # driver.find_element(By.XPATH,"//span[contains(text(),'mon')]").click()

    driver.find_element(By.XPATH,"//input[@id='flexCheckDefault']").click()
    driver.find_element(By.XPATH,"//button[contains(text(),'Save')]").click()
    time.sleep(5)
    for i in range(2):
        prompt_alert = driver.switch_to.alert
        prompt_alert.accept()
        time.sleep(5)
@pytest.mark.skip()
def test_locations(test_chupshop):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(5)
    driver.find_element(By.XPATH,"//h4[contains(text(),'Nashboro Fest')]").click()
    time.sleep(10)
    driver.find_element(By.XPATH,"//button[contains(text(),' Add More Location')]").click()
    time.sleep(5)
    driver.find_element(By.NAME, "address1").send_keys("3244")
    time.sleep(5)
    address=driver.find_element(By.XPATH, "//ul[@style='display: block;']/li[2]").click()
    time.sleep(5)
    # else:
    #     prompt_alert = driver.switch_to.alert
    #     prompt_alert.accept()
    #     time.sleep(5)
    driver.find_element(By.NAME, "slotName").send_keys("Breakfast")
    driver.find_element(By.NAME, "openTime").send_keys("08:00")
    driver.find_element(By.NAME, "closeTime").send_keys("11:30")
    time.sleep(10)
    driver.find_element(By.XPATH, "//button[contains(text(),'Set This Time For All Days')]").click()
    time.sleep(4)
    prompt_alert = driver.switch_to.alert
    prompt_alert.accept()
    time.sleep(5)
    driver.find_element(By.ID,"flexCheckDefault").click()
    save=driver.find_element(By.XPATH, "//body/div[3]/div[1]/div[1]/div[2]/div[1]/div[5]/button[1]")
    # driver.execute_script("arguments[0].scrollIntoView(true)", save)
    save.click()
    time.sleep(4)
    prompt_alert = driver.switch_to.alert
    prompt_alert.accept()
    time.sleep(5)
@pytest.mark.skip()
def test_chef(test_chupshop):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(5)
    driver.find_element(By.XPATH, "//h4[contains(text(),'Chups festival')]").click()
    time.sleep(10)
    driver.execute_script("window.scrollTo(0,250)")
    time.sleep(4)
    driver.find_element(By.XPATH,"//button[contains(text(),' Create Chef')]").click()
    time.sleep(4)
    driver.find_element(By.NAME,"chefName").send_keys("Test")
    driver.find_element(By.NAME,"email").send_keys("test@yah.com")
    driver.find_element(By.NAME,"Password").send_keys("12345678")
    time.sleep(5)
    driver.find_element(By.XPATH,"//body[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]").click()
    time.sleep(4)
    prompt_alert = driver.switch_to.alert
    prompt_alert.accept()
    time.sleep(5)
@pytest.mark.skip
def test_packer(test_chupshop):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(5)
    driver.find_element(By.XPATH, "//h4[contains(text(),'Chups festival')]").click()
    time.sleep(10)
    driver.execute_script("window.scrollTo(0,300)")
    time.sleep(4)
    driver.find_element(By.XPATH, "//button[contains(text(),' Create Packers')]").click()
    time.sleep(4)
    driver.find_element(By.NAME, "packersName").send_keys("packer")
    driver.find_element(By.NAME, "userName").send_keys("dan@g.com")
    driver.find_element(By.NAME, "password").send_keys("12345678")
    time.sleep(5)
    driver.find_element(By.XPATH,"//body/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]").click()
    time.sleep(4)
    prompt_alert = driver.switch_to.alert
    prompt_alert_text = prompt_alert.text
    print(prompt_alert_text)
    prompt_alert.accept()
    time.sleep(5)
@pytest.mark.skip()
def test_delivery_executive(test_chupshop):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(5)
    driver.find_element(By.XPATH, "//h4[contains(text(),'Chups festival')]").click()
    time.sleep(10)
    driver.execute_script("window.scrollTo(0,400)")
    time.sleep(4)
    driver.find_element(By.XPATH, "//button[contains(text(),' Create Delivery Executive')]").click()
    time.sleep(4)
    driver.find_element(By.NAME, "deliveryExeName").send_keys("delivery person")
    driver.find_element(By.NAME, "userName").send_keys("deliveer@g.co")
    driver.find_element(By.NAME, "password").send_keys("12345678")
    time.sleep(5)
    driver.find_element(By.XPATH,"//body[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]").click()
    time.sleep(4)
    prompt_alert = driver.switch_to.alert
    prompt_alert_text = prompt_alert.text
    print(prompt_alert_text)
    prompt_alert.accept()
    time.sleep(5)
@pytest.mark.skip()
def test_vendor(test_chupshop):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(5)
    driver.find_element(By.XPATH, "//h4[contains(text(),'Chups festival')]").click()
    time.sleep(10)
    driver.execute_script("window.scrollTo(0,800)")
    time.sleep(5)
    driver.find_element(By.XPATH, "//button[contains(text(),' Create Vendors')]").click()
    time.sleep(4)

    driver.find_element(By.NAME, "vendorName").send_keys("Jinkys")
    driver.find_element(By.NAME, "contactPersonName").send_keys("hello")
    driver.find_element(By.NAME,"contactPersonMobile").send_keys("0000202022")
    driver.find_element(By.NAME,"contactPersonEmail").send_keys("hello@g.com")
    time.sleep(5)
    driver.find_element(By.NAME, "address1").send_keys("36")
    time.sleep(5)
    address = driver.find_element(By.XPATH, "//ul[@style='display: block;']/li[1]").click()
    time.sleep(5)
    vendor_img=driver.find_element(By.XPATH,"//input[@class='jsx-609c67ed5b6d4de8']")
    vendor_img.send_keys("C:\\Users\\Skoruz-YogeshwariS\\PycharmProjects\\pythonProject\\chups\\download.jfif")
    time.sleep(5)
    driver.find_element(By.XPATH,"//body/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]").click()
    time.sleep(4)
    prompt_alert = driver.switch_to.alert
    prompt_alert_text = prompt_alert.text
    print(prompt_alert_text)
    prompt_alert.accept()
    time.sleep(5)
@pytest.mark.skip()
def test_addtable(test_chupshop):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(5)
    driver.find_element(By.XPATH, "//h4[contains(text(),'Chups festival')]").click()
    time.sleep(10)
    driver.execute_script("window.scrollTo(0,1000)")
    time.sleep(5)
    driver.find_element(By.XPATH, "//button[contains(text(),'Table')]").click()
    time.sleep(4)
    driver.find_element(By.XPATH,"//input[@placeholder='Table Name']").send_keys("Table1")
    driver.find_element(By.XPATH,"//input[@placeholder='Seat(s)']").send_keys("4")
    driver.find_element(By.XPATH,"//body/div[3]/div[1]/div[1]/div[2]/div[1]/div[3]/button[2]").click()
    time.sleep(4)
    prompt_alert = driver.switch_to.alert
    prompt_alert_text = prompt_alert.text
    print(prompt_alert_text)
    prompt_alert.accept()
    time.sleep(5)
    driver.find_element(By.XPATH, "//button[contains(text(),'Table')]").click()
    time.sleep(4)
    driver.find_element(By.XPATH, "//input[@placeholder='Table Name']").send_keys("Table2")
    driver.find_element(By.XPATH, "//input[@placeholder='Seat(s)']").send_keys("7")
    driver.find_element(By.XPATH,"//label[contains(text(),'Yes')]").click()
    driver.find_element(By.XPATH,"//div[@class='jsx-2865445288 d-flex align-items-center key-input']")
    driver.find_element(By.XPATH,"//input[@class='jsx-2865445288 form-control me-3']").send_keys("205")
    time.sleep(5)

    driver.find_element(By.XPATH,"//body/div[3]/div[1]/div[1]/div[2]/div[1]/div[4]/div[1]/input[1]").send_keys("Park hotel")
    time.sleep(4)
    driver.find_element(By.ID,"exampleForm.ControlInput1").send_keys("Breakfast")
    driver.find_element(By.NAME,"openTime").send_keys("08:00")
    driver.find_element(By.NAME,"closeTime").send_keys("11.30")
    time.sleep(5)
    driver.find_element(By.XPATH, "//body/div[3]/div[1]/div[1]/div[2]/div[1]/div[6]/button[2]").click()
    time.sleep(4)
    prompt_alert = driver.switch_to.alert
    prompt_alert_text = prompt_alert.text
    print(prompt_alert_text)
    prompt_alert.accept()
    time.sleep(5)
@pytest.mark.skip()
def test_waiter(test_chupshop):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(5)
    driver.find_element(By.XPATH, "//h4[contains(text(),'Chups festival')]").click()
    time.sleep(10)
    driver.execute_script("window.scrollTo(0,1200)")
    time.sleep(5)
    driver.find_element(By.XPATH,"//button[contains(text(),' Waiter')]").click()
    time.sleep(5)
    driver.find_element(By.XPATH,"//input[@placeholder='Name']").send_keys("Waiter1")
    driver.find_element(By.XPATH,"//input[@placeholder='Email']").send_keys("waiter01@g.com")
    driver.find_element(By.XPATH,"//input[@placeholder='Password']").send_keys("12341233")
    driver.find_element(By.XPATH,"//body[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]").click()
    time.sleep(4)
    prompt_alert = driver.switch_to.alert
    prompt_alert.accept()
    time.sleep(5)
    driver.find_element(By.XPATH, "//button[contains(text(),' Waiter')]").click()
    time.sleep(5)
    driver.find_element(By.XPATH, "//input[@placeholder='Name']").send_keys("Waiter2")
    driver.find_element(By.XPATH, "//input[@placeholder='Email']").send_keys("waiter02@g.com")
    driver.find_element(By.ID,"inline-radio-2").click()
    driver.find_element(By.XPATH, "//input[@placeholder='Pin']").send_keys("123")
    driver.find_element(By.XPATH, "//body[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]").click()
    time.sleep(4)
    prompt_alert = driver.switch_to.alert
    prompt_alert.accept()
    time.sleep(5)
@pytest.mark.skip()
def test_tips(test_chupshop):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(5)
    driver.find_element(By.XPATH, "//h4[contains(text(),'Chups festival')]").click()
    time.sleep(10)
    driver.execute_script("window.scrollTo(0,1500)")
    time.sleep(5)
    driver.find_element(By.XPATH,"//div[@class='ps-0 col-md-3 col-4']")
    percentage=driver.find_elements(By.XPATH,"//input[@id='formPlaintextPassword']")
    percentage[0].send_keys("5")
    percentage[1].send_keys("Good")
    percentage[2].send_keys("10")
    percentage[3].send_keys("Better")
    percentage[4].send_keys("15")
    percentage[5].send_keys("OMG")
    percentage[6].send_keys("20")
    percentage[7].send_keys("Excellent")
    driver.find_element(By.XPATH,"//button[contains(text(),'Save')]").click()
    time.sleep(4)
    prompt_alert = driver.switch_to.alert
    prompt_alert.accept()
    time.sleep(5)

def test_ham(test_chupshop):
    driver.find_element(By.XPATH,"//img[@class='mr-sm-4 mr-3 sidemenubaricon']").click()
    time.sleep(4)
    driver.find_element(By.XPATH,"//li[contains(text(),'Reports')]").click()
    time.sleep(10)
    driver.find_element(By.XPATH,"//button[@id='dropdown-basic']").click()
    time.sleep(5)
    driver.find_element(By.LINK_TEXT,"Item Sales Report").click()
    time.sleep(5)
    cal=driver.find_elements(By.XPATH,"//div[@class='jsx-152e353ea53c91d0 form-control inpucal d-flex align-items-center']")
    cal[0].click()
    driver.find_element(By.XPATH,"//abbr[@aria-label='June 1, 2023']").click()
    time.sleep(5)
    cal[1].click()
    driver.find_element(By.XPATH, "//abbr[@aria-label='June 20, 2023']").click()
    time.sleep(10)
    driver.find_element(By.XPATH,"//button[contains(text(),'View report')]").click()
    time.sleep(10)
    driver.find_element(By.LINK_TEXT,"Export as excel").click()
    time.sleep(5)
@pytest.mark.skip()
def test_brand(test_chupshop):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(5)
    driver.find_element(By.XPATH, "//h4[contains(text(),'Chups festival')]").click()
    time.sleep(10)
    driver.execute_script("window.scrollTo(0,800)")
    time.sleep(5)
    driver.find_element(By.XPATH,"//h3[contains(text(),'Yogi')]").click()
    time.sleep(10)
    driver.find_element(By.XPATH,"//button[contains(text(),'Add Brand')]").click()
    time.sleep(5)
    brand_img=driver.find_element(By.XPATH,"//input[@class='jsx-cd058ddc91eba0f6']")
    brand_img.send_keys("C:\\Users\\Skoruz-YogeshwariS\\PycharmProjects\\pythonProject\\chups\\download.png")
    time.sleep(4)
    driver.find_element(By.NAME, "brandName").send_keys("Chennai Tiffins")
    driver.find_element(By.NAME, "cuisine").send_keys("Indian")
    driver.find_element(By.NAME, "tagLine").send_keys("Indian")
    driver.find_element(By.NAME, "brandDesc").send_keys("South Indian Dishes")
    driver.find_element(By.NAME, "closingMessage").send_keys("Sold Out")
    time.sleep(6)
    pos_img=driver.find_element(By.XPATH, "//input[@class='jsx-cd058ddc91eba0f6']")
    pos_img.send_keys("C:\\Users\\Skoruz-YogeshwariS\\PycharmProjects\\pythonProject\\chups\\download.png")
    time.sleep(5)
    driver.find_element(By.NAME,"prepTime").send_keys("00:20:00")
    driver.find_element(By.XPATH,"//span[@class='jsx-cd058ddc91eba0f6 slider round']").click()
    driver.find_element(By.XPATH,"//button[contains(text(),'Save')]").click()
    time.sleep(4)
    prompt_alert = driver.switch_to.alert
    prompt_alert.accept()
    time.sleep(5)
@pytest.mark.skip()
def test_add_item(test_chupshop):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(5)
    driver.find_element(By.XPATH, "//h4[contains(text(),'Chups festival')]").click()
    time.sleep(10)
    driver.execute_script("window.scrollTo(0,800)")
    time.sleep(5)
    driver.find_element(By.XPATH, "//h3[contains(text(),'Yogi')]").click()
    time.sleep(10)
    driver.find_element(By.XPATH,"//h3[contains(text(),'Chennai Tiffins')]").click()
    time.sleep(5)
    driver.find_element(By.CLASS_NAME,"staging-btn text-uppercase").click()
    time.sleep(5)
    driver.find_element(By.XPATH,"//h4[contains(text(),'Food Items')]").click()
    driver.find_element(By.NAME,"item_name").send_keys("Idly")
    driver.find_element(By.NAME, "item_short_name").send_keys("I")




